name: 'Chromatic'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install Bun and PNPM globally
        run: npm install -g bun pnpm
      - name: Install Dependencies
        run: bun install --no-cache
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: chpt_845c7a47afdb884
          exitOnceUploaded: true
          exitZeroOnChanges: true
